### PR TITLE
Add 29-bit support

### PR DESCRIPTION
**Pull request by synaptic**
Add 29-bit support.  Modify preprocessor def SUPPORTS_29BIT to 1 to enable.  Not extensively tested yet, but filtering 11-bit messages under 29-bit mode works.  Check out the new docs in SerialCommand.h for serial API usage.

### CODE REVIEW

**Comment by eiannone** [comment]
Warning @etx  and @synaptic , this pull request contains a lot of regressions. Please check it!
You should always pull the latest upstream version and do a merge before submitting a pull request!

**Comment by synaptic** [comment]
I thought I did that but something may have gone wrong when I did the merge.  I only noticed some indenting issues afterwards.  I'll take a closer look and commit any changes I see missing.

**Comment by etx** [comment]
Awesome, Can't wait to check this out!

On a suggestion from @Wackerbarth we rebased the build files out of the repo history. So be sure your local repo is up to date. Maybe @Wackerbarth can give us some insight as well.

**Comment by Wackerbarth** [comment]
First a comment on the rebasing:

When you distribute a software/firmware product, there are three types of files involved.
The first type is the SOURCE. -- Given these source files (and the appropriate compilers) you can recreate the following additional types of files.
The next type of file is an INTERMEDIATE file (such as the compiled object files) -- These are not archived anywhere. They are regenerated from the source when needed.
The final type of file is a PRODUCT file (such as the .hex file used to flash the firmware into a device)
These are often distributed for the convenience of the end user. They don't have to be archived because, like the intermediate files, they can be regenerated.
However, it is often desirable to keep a few versions of them in an archive, either as a distribution mechanism, or as a convenience.

Now, it should be noted that unlike the incremental changes in the source, these large files usually have little in common, iteration to iteration. Therefore, storing the files themselves may have value, but attempting to store the incremental change history is rather meaningless.

Additionally, the files become "stale". It is highly unlikely that anyone will care about having available all of the obsolete versions.  If the files are simply stored on a mass storage device, the obsolete ones can be deleted when they are no longer useful. And should a previously deleted file be needed, it can be regenerated from the source.

Now we come to the use of "git", or any other source management system. It works well for our source files. But if the product files are intermingled, it cannot "forget" the unnecessary ones.

By keeping the product files in a separate repository, you eliminate the burden (space and transfer time) placed on those who are working with the source repository.

The rebasing was a "clean-up" to eliminate "history" of those files which are not source files.

(See my next response for more about using the source repository to maintain a meaningful history.)

**Comment by synaptic** [comment]
I re-merged in attempt to get better, re-based master.  I'll close this and open another pull request.

**Pull request closed without merging**
